### ISSUE TITLE
Keepalives

### ISSUE THREAD

**Issue by tobyjaffey** [01org/liblwm2m#14]
Testing liblwm2m through NAT, I find that after a few minutes the client no longer receives packets sent by the server.

This appears to be because the NAT gateway's punched hole collapses, requiring keepalives.

My solution has been to implement a lwm2m_ping(lwm2m_context_t *) for the client which sends an empty CoAP message to the server. The application then needs to call this on a timer.

Is this the right way, or should an LWM2M client be doing keepalives as "UPDATE" messages? Or something else?

If my way is acceptable, I'll commit and raise a pull request.

Thanks.

**Comment by dnav** [comment]
Project moved to http://github.com/eclipse/wakaama
