### ISSUE TITLE
Porting to a non-linux device

### ISSUE THREAD

**Issue by cache91** [01org/liblwm2m#36]
Hey i am actually working on a project that invloves using the client application in a device which does not run on linux. Basically what i am looking for is to port this client code to an embedded device like the Arduino YUN or some other embedded device. But the problem is that this is project is for a linux device , it is difficult to do so. So any inputs/suggestions  would be helpful !

Thanks in advance
Cache

**Comment by dnav** [comment]
Project moved to http://github.com/eclipse/wakaama
