### ISSUE TITLE
Client deregistration issue

### ISSUE THREAD

**Issue by paulkeogh** [01org/liblwm2m#37]
Hi,

I think there may be an issue with client dereg. Consider the use case where a client registers and immediately deregisters (for whatever reason). There is a possibility that the client will not have handled the registration response from the server and hence not updated the status of the lwm2m_server_t instance to STATE_REGISTERED.

Consequently the deregistration by client will fail because in registration.c/registration_deregister() there is a line;

   if (serverP->status != STATE_REGISTERED) return;

Which causes the function to return without sending the dereg command.
The server is then left holding a reference to a client.

Is this a valid use case ?

**Comment by dnav** [comment]
Project moved to http://github.com/eclipse/wakaama
