### ISSUE TITLE
Blockwise Transfers in CoAP - draft-ietf-core-block-14

### ISSUE THREAD

**Issue by ConZ27** [01org/liblwm2m#40]
I am currently working on pushing updates via the Firmware Object (/5/0/0); however, messages are truncated at the 128 bytes as defined by REST_MAX_CHUNK_SIZE in er-coap.h.

<b>Current Behaviour</b>:
Firmware packages > 128 bytes truncated and only the first block of data is sent out.

<b>Expected Behaviour</b>:
Firmware package file should be fragmented into blocks and sent out in chunks.

The Contiki OS repository seems to have implemented this functionality - I think it just needs to be ported into here and integrated with the test client and server.

**Comment by dnav** [comment]
Project moved to http://github.com/eclipse/wakaama
